Changes has been made to the i2c inicialization
AdaCore/Ada_Drivers_Library pull request #402
Opened 2022-03-24 18:15 UTC by mbdme26

Hello,

I'm Mario Vicente García and i'm doing a project with the University of Cantabria, Spain. 

Carrying out tests to try to send data through the I2C bus to control the motors of the maqueen robot (https://tienda.bricogeek.com/microbit/1271-robot-maqueen-para-microbit.html) using your library and the Microbit V1.3x, we realized that the initialization of the GPIO pins (SCA and SCL) is done incorrectly.

Trying to do a succesful master_transmit to the maqueen address (0x20), the function returned us a 0 (ERROR). Doing an I2C bus probe to see all available addresses on the bus, we realized that only the accelerometer address was available (0x1D), but the compass and maqueen motors addresses were not available.

According to the next manual, the relevant configuration for the pins is the GPIO DRIVE:

https://infocenter.nordicsemi.com/pdf/nRF51_RM_v3.0.pdf   (p.145, table 258)

So, applying the configuration on the SCL and SDA pins and doing again the probe of the I2C bus. We managed to see all the bus addresses correctly and successfully perform a master_transmit to the Maqueen motors.

Regards,
Mario

2022-03-24 18:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AdaCore/Ada_Drivers_Library?pullRequest=402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AdaCore/Ada_Drivers_Library?pullRequest=402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AdaCore/Ada_Drivers_Library?pullRequest=402) it.</sub>

2022-03-31 15:26 UTC, Fabien-Chouteau requested changes
Thank you @mbdme26.

There are a few things to change but I agree with idea.

2022-03-31 15:26 UTC, Fabien-Chouteau commented on boards/MicroBit/src/microbit-i2c.adb
> +      Config   : GPIO_Configuration := (Mode => Mode_In,
`Config` should be `constant` as it is not modified.

Also you need to add `use nRF.GPIO` for the type to be visible.

2022-03-31 15:26 UTC, Fabien-Chouteau commented on boards/MicroBit/src/microbit-i2c.adb
> +      GPIO_Pin_SDA : GPIO_Point := (Pin => MB_SDA.Pin);
This variables are not needed. You can directly use `MB_SCL` and `MB_SDA` below.

2022-03-31 15:26 UTC, Fabien-Chouteau commented on boards/MicroBit/src/microbit-i2c.adb
> +      Configure_IO(GPIO_Pin_SDA, Config);
You can do:
```ada
      Configure_IO (MB_SCL, Config);
      Configure_IO (MB_SDA, Config);
```

2022-04-04 13:19 UTC, Fabien-Chouteau requested changes
Hello @mbdme26,

There are still two style issues. You should set the scenario variable `ADL_BUILD_CHECKS` to `Enabled` and recompile.

2022-04-04 13:19 UTC, Fabien-Chouteau commented on boards/MicroBit/src/microbit-i2c.adb
> +      --  Initialize the GPIO Pins for SCL & SDA
microbit-i2c.adb:72:19: (style) space required\nmicrobit-i2c.adb:73:19: (style) space required

2022-04-18 18:18 UTC, mbdme26 commented
I'm sorry for the delay @Fabien-Chouteau , Style issues should be fixed. If there's anything else I need to do, don't hesitate to tell me.

Regards,
Mario

2022-04-19 13:12 UTC, Fabien-Chouteau approved these changes

2022-04-19 13:12 UTC, merged

2022-04-19 13:12 UTC, Fabien-Chouteau commented
Thank you @mbdme26 :+1: