New component: text LCD
AdaCore/Ada_Drivers_Library pull request #405
Opened 2022-05-08 19:42 UTC by RREE

This patch add simple text based LCDs based on the HD44780 driver. Almost all text LCD use this or a compatible driver module. 

This first version uses a PCF8574 I/O expander via I²C. I can also add a 4bit implementation, but that requires 7 or 8 GPIOs of the controller. That's why I don't use it anymore.

As a prerequisite this patch requires the merge of the aforementioned PCF8574 pull request.

2022-05-08 19:48 UTC, RREE commented
I created the branch in my copy of the ADL off the branch for the pcf8574.  It seems that this pull request contains both the pcf8574 and the new LCD code

2022-05-30 13:37 UTC, Fabien-Chouteau requested changes
Hi @RREE, thanks for the contribution.
Besides the header this looks good to me.

I guess I can close the other PR for the PCF8574.

2022-05-30 13:37 UTC, Fabien-Chouteau commented on components/src/io_expander/pcf8574/pcf8574.ads
> +--
Same here.

2022-06-01 14:58 UTC, Fabien-Chouteau requested changes
There's an unreferenced with:
```
lcd_hd44780-pcf8574.ads:35:09: warning: unit "HAL.I2C" is not referenced 
```

You should run `scripts/build_all_examples.py` to check your patch.

2022-06-14 07:45 UTC, Fabien-Chouteau approved these changes

2022-06-14 07:45 UTC, merged

2022-06-14 07:45 UTC, Fabien-Chouteau commented
Thank you @RREE !